### ISSUE TITLE
FTS docker-compose issue

### ISSUE THREAD

**Issue by sorokaalex** [FreeTAKTeam/FreeTAKHub-Installation#130]
Hello Folks,

I´m trying to install FTS at my home lab using docker and I have some issues.

I´m using docker compose file from https://github.com/FreeTAKTeam/FreeTAKHub-Installation/blob/main/containers/example-compose.yaml 

 If I leave sqlite:////home/freetak/data/FTSServer-UI.db I cannot connect to UI and if I remove "data" and leave sqlite:////home/freetak/FTSServer-UI.db  I can connect but error message appear: Sorry, there seems to be an issue with the connection!

![FTS_Error](https://github.com/user-attachments/assets/e8d148ad-8e66-4163-8982-7c784ae588f0)

**Comment by Rushmore75** [comment]
I believe I'm having the same issue. This is the error I get when I got the <my-server-ip>:5000

```
Traceback (most recent call last):
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 660, in __connect
    with util.safe_reraise():
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/freetak/.local/lib/python3.11/site-packages/eventlet/wsgi.py", line 598, in handle_one_response
    result = self.application(self.environ, start_response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/flask/app.py", line 1815, in full_dispatch_request
    self.ensure_sync(func)()
  File "/home/freetak/.local/lib/python3.11/site-packages/FreeTAKServer-UI/app/__init__.py", line 33, in initialize_database
    db.create_all()
  File "/home/freetak/.local/lib/python3.11/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/freetak/.local/lib/python3.11/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 4664, in create_all
    bind._run_visitor(
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2094, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2086, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 660, in __connect
    with util.safe_reraise():
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freetak/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)

```

**Comment by FalconJK** [comment]
I tried this, it's work
https://github.com/FreeTAKTeam/FreeTAKHub-Installation/issues/124#issuecomment-3120967503
